# Generated by Django 5.1.3 on 2025-01-20 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensaje',
            options={'managed': False},
        ),
    ]
