# Generated by Django 5.1.3 on 2024-12-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_mensaje', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=20)),
                ('mensaje', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Certificados',
        ),
    ]
