# Generated by Django 5.1.3 on 2024-12-21 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_mensajes_delete_certificados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajes',
            name='fecha_mensaje',
        ),
    ]
