# Generated by Django 5.1.3 on 2024-12-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_mensajes_fecha_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajes',
            name='fecha_mensaje',
            field=models.DateTimeField(default='2024-12-21 16:56:55'),
        ),
    ]
