# Generated by Django 5.1.3 on 2024-12-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_mensajes_fecha_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='fecha_mensaje',
            field=models.DateTimeField(default='2024-12-23 11:40:54'),
        ),
    ]
